version: 2
updates:

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [dependencies]
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: '[dependency]'
