language: python

python:
  - 3.7

env:
  global:
    RELEASE_BRANCH=main

cache: pip

install:
  - pip install -r lint_requirements.txt
  - pip install -r requirements.txt

jobs:
  include:
    - stage: lint
      script:
        - isort --check-only --line-length 140 account client health history
        - pycodestyle --config=.pycodestyle -- account client health history
        - pylint --load-plugins pylint_quotes -- account client health history

    - stage: run account scripts
      script:
        - python -m account.symbol_multisig_create --input account/samples/symbol_multisig_create.yaml
        - python -m account.two_part_send --input account/samples/two_part_send.yaml
        - python -m account.verify_ownership --input account/samples/verify_ownership.yaml

    - stage: run health scripts
      script:
        - python -m health.check_nem_balances --resources templates/nem.mainnet.yaml --groups core
        - python -m health.check_nem_balances --resources templates/symbol.mainnet.yaml --groups core

    - stage: run history scripts (nem)
      if: branch = env(RELEASE_BRANCH)
      script:
        - python -m history.downloader --input templates/nem.mainnet.yaml --start-date 2021-08-01 --end-date 2021-08-31 --output _histout/raw
        - mkdir -p _histout/all
        - python -m history.merger --input _histout/raw --output _histout/all/full.csv --ticker nem
        - mkdir -p _histout/account
        - python -m history.grouper --input _histout/all/full.csv --output _histout/account/grouped.csv --mode account
        - python -m history.summarizer --input _histout/account --output _histout/balances.csv --mode account
        # not: reconciler will fail when there is only a partial download
        - python -m history.reconciler --input _histout/balances.csv --resources templates/nem.mainnet.yaml --mode spot || test $? -eq 1

    - stage: run history scripts (symbol)
      if: branch = env(RELEASE_BRANCH)
      script:
        - python -m history.downloader --input templates/symbol.mainnet.yaml --start-date 2021-08-01 --end-date 2021-08-31 --output _histout/raw
        - mkdir -p _histout/all
        - python -m history.merger --input _histout/raw --output _histout/all/full.csv --ticker symbol
        - mkdir -p _histout/account
        - python -m history.grouper --input _histout/all/full.csv --output _histout/account/grouped.csv --mode account
        - python -m history.summarizer --input _histout/account --output _histout/balances.csv --mode account
        # not: reconciler will fail when there is only a partial download
        - python -m history.reconciler --input _histout/balances.csv --resources templates/symbol.mainnet.yaml --mode spot || test $? -eq 3

    - stage: block lint
      script:
        - isort --check-only --line-length 140 account client health history
        - pycodestyle --config=.pycodestyle -- account client health history
        - pylint --load-plugins pylint_quotes -- account client health history
    
    - stage: run block extraction scripts (symbol)
      if: branch = env(RELEASE_BRANCH)
      script:
        - python -m block.extractor.extract --input block/data --output block/resources

    - stage: run harvester analysis scripts (symbol)
      if: branch = env(RELEASE_BRANCH)
      script:
        # note: will fail if extractor output is absent
        - python -m block.harvester.get_harvester_stats --input block/resources/accounts.json --state_path block/resources/state_map.msgpack --headers_path block/resources/block_header_df.pkl --output block/harvester/output

    - stage: run delegate analysis scripts (symbol)
      if: branch = env(RELEASE_BRANCH)
      script:
        # note: will fail if extractor output is absent
        - python -m block.delegates.find_delegates --input block/resources/accounts.json --state_path block/resources/state_map.msgpack --output block/delegates/output/delegates.json
